### ISSUE TITLE
Internal compiler error

### ISSUE THREAD

**Issue by vporton** [dfinity/motoko#4297]
(I am unsure why an old version 0.9.8 is being used. I even deleted `~/.cache/dfinity` and reinstalled DFX 0.15.1 anew.)

Checkout https://github.com/vporton/NacDBReorder/tree/182eac05f5249661fe65a14d86a31ccc32c1c009

Then in this repo, see `log.txt`.
[log.txt](https://github.com/dfinity/motoko/files/13480046/log.txt)

**Comment by crusso** [comment]
Ok, I took a look and can reproduce the error.

I narrowed it down to file 

test/main.mo
```
import RO "../src/Reorder";
import Nac "mo:nacdb/NacDB";
import M "mo:matchers/Matchers";
import T "mo:matchers/Testable";
import Suite "mo:matchers/Suite";
import Order "mo:base/Order";
import Index "index/main";
import MyCycles "mo:nacdb/Cycles";
import GUID "mo:nacdb/GUID";
import Common "common";

let index = await Index.Index();
MyCycles.addPart(Common.dbOptions.partitionCycles);
await index.init();

func prepareOrder(orderer: RO.Orderer): async* RO.Order {
    await* RO.createOrder(GUID.nextGuid(orderer.guidGen), {orderer});
};

func main() {
    let suite = Suite.suite("Reorder test", [
        Suite.suite("Nat tests", [
            Suite.test("10 is 10", 10, M.equals(T.nat(10))),
            Suite.test("5 is greater than three", 5, M.greaterThan<Nat>(3)),
        ])
    ]);
    Suite.run(suite);
};
```
which isn't expressed as an explicit actor yet is accepted by the compiler. This is actually a convenience feature for our own test suites, but should only be used for code that can also appear in the body of an actor.

In this example, that isn't actually true because of the top-level awaits and we should reject the code rather than munging it into an actor.

If you change your code to something like this all is well:

```
import RO "../src/Reorder";
import Nac "mo:nacdb/NacDB";
import M "mo:matchers/Matchers";
import T "mo:matchers/Testable";
import Suite "mo:matchers/Suite";
import Order "mo:base/Order";
import Index "index/main";
import MyCycles "mo:nacdb/Cycles";
import GUID "mo:nacdb/GUID";
import Common "common";

actor {

  public func test() : async () {
    let index = await Index.Index();
    MyCycles.addPart(Common.dbOptions.partitionCycles);
    await index.init();

    func prepareOrder(orderer: RO.Orderer): async* RO.Order {
      await* RO.createOrder(GUID.nextGuid(orderer.guidGen), {orderer});
    };

    func main() {
      let suite = Suite.suite("Reorder test", [
        Suite.suite("Nat tests", [
        Suite.test("10 is 10", 10, M.equals(T.nat(10))),
        Suite.test("5 is greater than three", 5, M.greaterThan<Nat>(3)),
      ])
    ]);
    Suite.run(suite);
    };

    main();
  }
}
```
But we should obviously fix the compiler to reject your original code, or handle it better.

**Comment by crusso** [comment]
Minimal repro:

issue-4297.mo
```
await async {};
```

```
[nix-shell:~/motoko/test/run-drun]$ moc issue-4297.mo 
OOPS! You've triggered a compiler bug.
Please report this at https://github.com/dfinity/motoko/issues/new with the following details:

Motoko (source 0.10.2-8-g4346ef188)

Fatal error: exception File "codegen/compile.ml", line 8601, characters 11-17: Assertion failed
Raised at Codegen__Compile.Internals.call_prelude_function in file "codegen/compile.ml", line 8601, characters 11-23
Called from Codegen__Compile.Internals.add_cycles in file "codegen/compile.ml" (inlined), line 8603, characters 26-68
Called from Codegen__Compile.compile_exp_with_hint in file "codegen/compile.ml", line 11380, characters 21-48
Called from Codegen__Compile.compile_exp_as_opt in file "codegen/compile.ml", line 11417, characters 20-59
...
```

**Comment by sanderwill** [comment]
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 


java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5
 at org.nlogo.agent.Patch.setPatchVariable(Patch.java:242)
 at org.nlogo.agent.Turtle.setPatchVariable(Turtle.java:527)
 at org.nlogo.prim._asm_procedurego_setpatchvariable_13.perform(:1)
 at org.nlogo.nvm.Context.runExclusive(Context.java:133)
 at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.scala:39)
 at org.nlogo.nvm.Context.runExclusiveJob(Context.java:177)
 at org.nlogo.prim._asm_procedurego_ask_9.perform(:1)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at scala.util.control.Exception$Catch.apply(Exception.scala:228)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.3.0
main: org.nlogo.app.AppFrame
thread: JobThread
OpenJDK 64-Bit Server VM 17.0.4 (BellSoft; 17.0.4+8-LTS)
operating system: Mac OS X 10.15.7 (x86_64 processor)
Scala version 2.12.16
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

11:23:41.935 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
11:23:41.935 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
11:23:41.883 RuntimeErrorEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:23:41.882 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
11:23:41.864 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:23:41.864 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:23:41.864 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:23:41.663 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:23:41.663 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:23:41.663 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by crusso** [comment]
Tentative fix in #4306
